# Generated by Django 4.1.7 on 2023-02-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20, unique=True)),
                ('product_title', models.CharField(max_length=30)),
                ('product_category', models.CharField(max_length=30)),
                ('product_rating', models.CharField(max_length=30)),
                ('product_price', models.CharField(max_length=30)),
                ('product_description', models.TextField()),
                ('product_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
