# Generated by Django 4.1.7 on 2023-04-01 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_Admin', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category_main',
            field=models.TextField(choices=[('Consumable', 'Consumable'), ('Non-Consumable', 'Non-Consumable')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(to='app_Admin.category'),
        ),
    ]
