# Generated by Django 4.1.5 on 2023-01-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
