# Generated by Django 4.1.5 on 2023-01-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='face',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.IntegerField(default=0)),
                ('bad', models.IntegerField(default=0)),
                ('best', models.IntegerField(default=0)),
            ],
        ),
    ]
